var data = [
    {
        key: '0',
        zaman: '08:30-09:00',
        pazartesi: '',
        salı: '',
        carsamba: '',
        persembe: '',
        cuma: '',
    },
    {
        key: '1',
        zaman: '09:00-09:30',
        pazartesi: '',
        salı: '',
        carsamba: '',
        persembe: '',
        cuma: '',
    },
    {
        key: '2',
        zaman: '09:30-10:00',
        pazartesi: '',
        salı: '',
        carsamba: '',
        persembe: '',
        cuma: '',
    },
    {
        key: '3',
        zaman: '10:00-10:30',
        pazartesi: '',
        salı: '',
        carsamba: '',
        persembe: '',
        cuma: '',
    },
    {
        key: '4',
        zaman: '10:30-11:00',
        pazartesi: '',
        salı: '',
        carsamba: '',
        persembe: '',
        cuma: '',
    },
    {
        key: '5',
        zaman: '11:00-11:30',
        pazartesi: '',
        salı: '',
        carsamba: '',
        persembe: '',
        cuma: '',
    },
    {
        key: '6',
        zaman: '11:30-12:00',
        pazartesi: '',
        salı: '',
        carsamba: '',
        persembe: '',
        cuma: '',
    },
    {
        key: '7',
        zaman: '12:00-12:30',
        pazartesi: '',
        salı: '',
        carsamba: '',
        persembe: '',
        cuma: '',
    },
    {
        key: '8',
        zaman: '12:30-13:00',
        pazartesi: '',
        salı: '',
        carsamba: '',
        persembe: '',
        cuma: '',
    },
    {
        key: '9',
        zaman: '13:00-13:30',
        pazartesi: '',
        salı: '',
        carsamba: '',
        persembe: '',
        cuma: '',
    },
    {
        key: '10',
        zaman: '13:30-14:00',
        pazartesi: '',
        salı: '',
        carsamba: '',
        persembe: '',
        cuma: '',
    },
    {
        key: '11',
        zaman: '14:00-14:30',
        pazartesi: '',
        salı: '',
        carsamba: '',
        persembe: '',
        cuma: '',
    },
    {
        key: '12',
        zaman: '14:30-15:00',
        pazartesi: '',
        salı: '',
        carsamba: '',
        persembe: '',
        cuma: '',
    },
    {
        key: '13',
        zaman: '15:00-15:30',
        pazartesi: '',
        salı: '',
        carsamba: '',
        persembe: '',
        cuma: '',
    },
    {
        key: '14',
        zaman: '15:30-16:00',
        pazartesi: '',
        salı: '',
        carsamba: '',
        persembe: '',
        cuma: '',
    },
    {
        key: '15',
        zaman: '16:00-16:30',
        pazartesi: '',
        salı: '',
        carsamba: '',
        persembe: '',
        cuma: '',
    },
    {
        key: '16',
        zaman: '16:30-17:00',
        pazartesi: '',
        salı: '',
        carsamba: '',
        persembe: '',
        cuma: '',
    },
    {
        key: '17',
        zaman: '17:00-17:30',
        pazartesi: '',
        salı: '',
        carsamba: '',
        persembe: '',
        cuma: '',
    }
]


export default data;